### ISSUE TITLE
ikinci arama hatası

### ISSUE THREAD

**Issue by us** [barissaslan/django-dersleri#1]
mesela bi arama yaptık ve http://127.0.0.1:8000/post/index/?q=ilk+sorgu buna yönlendirildik daha sonra tekrardan arama butonundan başka bi arama yaptığımızda hata alıyorum çünkü şu linke yönlendiriyor http://127.0.0.1:8000/post/index/ilk%20sorgu?q=ikinci+sorgu ilk sorguyu '?q' nun önene atıyor

**Comment by barissaslan** [comment]
Bende sonuçlar şu şekilde :
ilk aramada url :  http://127.0.0.1:8000/post/index/?q=arama1
ikinci aramada url :  http://127.0.0.1:8000/post/index/?q=arama2
Olması gerekende bu şekilde. İkinci bir aramada hata vermemesi lazım. Kodlarınızı kontrol eder misiniz?

**Comment by us** [comment]
commitlerden kontrol ettim benim kodum hatalıymış teşekkürler

**Comment by barissaslan** [comment]
Rica ederim, kolay gelsin.
