### ISSUE TITLE
static file hatası

### ISSUE THREAD

**Issue by us** [barissaslan/django-dersleri#2]
/etc/nginx/sites-available/blog dosyasının içeriği şu şekilde ;

   ```
 server {
    listen 80;
    server_name 35.188.97.4;
    location = /favicon.ico { access_log off; log_not_found off; }
    location /static/ {
        root /home/syny/blog;
    }

    location / {
        include         uwsgi_params;
        uwsgi_pass      unix:/run/uwsgi/blog.sock;
    }
}
```

manage.py den runserver la çalıştırdığımda static dosyaları alıyor mesela ck editor çalışıyor fakat nginx ile çalıştırdığımda ckeditor çalışmıyor hatanın buradan olabilceğini düşündüm '/static/' yerini '/static/' files da yaptım fakat hala daha çalıştıramıyorum setting dosyasında mı değişiklik yapmam gerekiyor . blog/setting.py dosyasında da şöyle:

```
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
```

**Comment by us** [comment]
![screen shot 2017-07-08 at 22 26 31](https://user-images.githubusercontent.com/22618852/27988546-9861e25e-642c-11e7-9fbf-88c48ca69742.png)
mesela admin paneli olarak django jet yüklemiştim ve görüntü şu şekilde oluyor nginx ile çalıştırdğım zaman

**Comment by barissaslan** [comment]
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

satırını silip tekrar dener misiniz? STATICFILES_DIRS parametresini sadece development ortamında kullanıyoruz.

**Comment by us** [comment]
çalıştı teşekkür ederim
